ChartValues:
  gitlabUrl: ${GitlabUrl}
  runners:
    privileged: true
    image: alpine:latest
    builds:
      enabled: true
    config: |
      [[runners]]
        name = "kubernetes-runner"
        executor = "kubernetes"
        namespace = "gitlab-runner"
        ephemeral_storage_request = "30Gi"
        ephemeral_storage_limit = "30Gi"
        [runners.cache]
          type = "s3"
          shared = true
          [runners.cache.s3]
            ServerAddress = "oss-ap-southeast-1.aliyuncs.com"
            AccessKey = "${OssAccessKey}"
            SecretKey = "${OssSecretKey}"
            BucketName = "gitlab-renyun-runner"
            BucketLocation = "ap-southeast-1"
            Insecure = false
        [runners.kubernetes]
          namespace = "gitlab-runner"
          cpu_limit = "2"
          cpu_request = "2"
          memory_limit = "4Gi"
          memory_request = "4Gi"
          pod_labels_overwrite_allowed = ".*"
          [runners.kubernetes.pod_labels]
            "app" = "acs-gitlab-runner"
            "alibabacloud.com/compute-qos" = "best-effort"
            "alibabacloud.com/compute-class" = "general-purpose"
        [[runners.feature_flags]]
          FF_USE_POD_ACTIVE_DEADLINE_SECONDS = true
    tags: kubernetes,k8s
  runnerRegistrationToken: ${GitlabRunnerToken}
HelmChartPath: a
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: LYH-RAIN/gitlab-runner-test
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: LYH-RAIN
Branch: main
Platform: github
